name: creates
favicon: null
layout_spectrum: 0.18543
typography_spectrum: 0.5985727764200419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060709'
    - '#747c89'
    - '#3d434f'
    - '#cce1f6'
  brandStrength: 0.25
  lightness: 0.25
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
